export default {
  year: '2024',
  belong: '工学部　情報・知能工学課程　３年次入学 3年',
  semester: 'fall',
  firstHalf: [
    [
      {
        id: 'B13630160',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630160&je_cd=1',
        name: 'プログラム言語論',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '梅村　恭司',
      },
      {
        id: 'B13630240',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630240&je_cd=1',
        name: '多変量解析論',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '岡田  美智男',
      },
      {
        id: 'B13630190',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630190&je_cd=1',
        name: '制御工学',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '福村  直博',
      },
      null,
      null,
    ],
    [
      {
        id: 'B13630270',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630270&je_cd=1',
        name: 'オペレーティングシステム',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '大村　廉',
      },
      null,
      null,
      null,
      {
        id: 'B1033035d',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B1033035d&je_cd=1',
        name: '英語 Reading & Writing Ⅳ',
        required: '[英語]',
        term: '後期',
        units: '1単位',
        staff: 'Levin David Michael',
      },
    ],
    [
      null,
      null,
      {
        id: 'B13630280',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630280&je_cd=1',
        name: 'コンパイラ',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '秋葉  友良',
      },
      {
        id: 'B13630030',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630030&je_cd=1',
        name: '数値解析論',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '南　哲人',
      },
      {
        id: 'B13610100',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13610100&je_cd=1',
        name: '情報・知能工学実験',
        required: '[必修]',
        term: '通年',
        units: '4単位',
        staff: 'Ｓ３系教務委員',
      },
    ],
    [
      {
        id: 'B13630210',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630210&je_cd=1',
        name: 'ソフトウェア設計論',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '佐藤　幸紀',
      },
      null,
      {
        id: 'B13630250',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630250&je_cd=1',
        name: '情報セキュリティ',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '鈴木　幸太郎',
      },
      null,
      {
        id: 'B13610100',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13610100&je_cd=1',
        name: '情報・知能工学実験',
        required: '[必修]',
        term: '通年',
        units: null,
        staff: 'Ｓ３系教務委員',
      },
    ],
    [
      {
        id: 'B13630330',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630330&je_cd=1',
        name: 'ディジタル信号処理',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '松井　淑恵',
      },
      null,
      null,
      {
        id: 'B13630220',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630220&je_cd=1',
        name: 'データベース',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '南　哲人',
      },
      {
        id: 'B13610100',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13610100&je_cd=1',
        name: '情報・知能工学実験',
        required: '[必修]',
        term: '通年',
        units: null,
        staff: 'Ｓ３系教務委員',
      },
    ],
    [
      null,
      {
        id: 'B13630370',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630370&je_cd=1',
        name: 'データサイエンス演習基礎',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '1単位',
        staff: '原田  耕治',
      },
      null,
      null,
      null,
    ],
  ],
  secondHalf: [
    [
      {
        id: 'B13630160',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630160&je_cd=1',
        name: 'プログラム言語論',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '梅村　恭司',
      },
      {
        id: 'B13630240',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630240&je_cd=1',
        name: '多変量解析論',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '岡田  美智男',
      },
      {
        id: 'B13630190',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630190&je_cd=1',
        name: '制御工学',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '福村  直博',
      },
      null,
      null,
    ],
    [
      {
        id: 'B13630270',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630270&je_cd=1',
        name: 'オペレーティングシステム',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '大村　廉',
      },
      null,
      null,
      null,
      {
        id: 'B1033035d',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B1033035d&je_cd=1',
        name: '英語 Reading & Writing Ⅳ',
        required: '[英語]',
        term: '後期',
        units: '1単位',
        staff: 'Levin David Michael',
      },
    ],
    [
      null,
      null,
      {
        id: 'B13630280',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630280&je_cd=1',
        name: 'コンパイラ',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '秋葉  友良',
      },
      {
        id: 'B13630030',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630030&je_cd=1',
        name: '数値解析論',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '南　哲人',
      },
      {
        id: 'B13610100',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13610100&je_cd=1',
        name: '情報・知能工学実験',
        required: '[必修]',
        term: '通年',
        units: '4単位',
        staff: 'Ｓ３系教務委員',
      },
    ],
    [
      {
        id: 'B13630210',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630210&je_cd=1',
        name: 'ソフトウェア設計論',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '佐藤　幸紀',
      },
      null,
      {
        id: 'B13630250',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630250&je_cd=1',
        name: '情報セキュリティ',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '鈴木　幸太郎',
      },
      null,
      {
        id: 'B13610100',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13610100&je_cd=1',
        name: '情報・知能工学実験',
        required: '[必修]',
        term: '通年',
        units: null,
        staff: 'Ｓ３系教務委員',
      },
    ],
    [
      {
        id: 'B13630330',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630330&je_cd=1',
        name: 'ディジタル信号処理',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '松井　淑恵',
      },
      null,
      null,
      {
        id: 'B13630220',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630220&je_cd=1',
        name: 'データベース',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '南　哲人',
      },
      {
        id: 'B13610100',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13610100&je_cd=1',
        name: '情報・知能工学実験',
        required: '[必修]',
        term: '通年',
        units: null,
        staff: 'Ｓ３系教務委員',
      },
    ],
    [
      null,
      {
        id: 'B13630370',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630370&je_cd=1',
        name: 'データサイエンス演習基礎',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '1単位',
        staff: '原田  耕治',
      },
      null,
      null,
      null,
    ],
  ],
  intensive: [
    [null, null, null, null, null, null],
    [null, null, null, null, null, null],
    [null, null, null, null, null, null],
  ],
};
