export default {
  belong: '工学部　情報・知能工学課程　３年次入学 3年',
  year: '2024',
  term: 'fall',
  firstHalf: [
    [
      {
        id: 'B13630160',
        name: 'プログラム言語論',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630160&je_cd=1',
        status: 'enrolled',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '梅村　恭司',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
      {
        id: 'B13630240',
        name: '多変量解析論',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630240&je_cd=1',
        status: 'enrolled',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '岡田  美智男',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
      {
        id: 'B13630190',
        name: '制御工学',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630190&je_cd=1',
        status: 'enrolled',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '福村  直博',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
      {
        id: 'B10233610',
        name: '健康科学',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B10233610&je_cd=1',
        status: 'lot_rejected',
        required: '[選択]',
        term: '後期',
        units: '2単位',
        staff: '小島　俊男',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
      {
        id: 'B10233553',
        name: '欧米文化論',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B10233553&je_cd=1',
        status: 'lot_rejected',
        required: '[選択]',
        term: '後期',
        units: '2単位',
        staff: '社河内　友里',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
    ],
    [
      {
        id: 'B13630270',
        name: 'オペレーティングシステム',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630270&je_cd=1',
        status: 'enrolled',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '大村　廉',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
      null,
      {
        id: 'B1042504o',
        name: '国語表現法',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B1042504o&je_cd=1',
        status: 'lot_rejected',
        required: '[選択必修Ⅱ]',
        term: '後期',
        units: '2単位',
        staff: '日比野  浩信',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
      null,
      {
        id: 'B1033035d',
        name: '英語 Reading & Writing Ⅳ',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B1033035d&je_cd=1',
        status: 'enrolled',
        required: '[英語]',
        term: '後期',
        units: '1単位',
        staff: 'Levin David Michael',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
    ],
    [
      {
        id: 'B1033207a',
        name: 'フランス語Ⅲ',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B1033207a&je_cd=1',
        status: 'lot_rejected',
        required: '[フランス語]',
        term: '後期',
        units: '1単位',
        staff: '山崎  由佳',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
      null,
      {
        id: 'B13630280',
        name: 'コンパイラ',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630280&je_cd=1',
        status: 'enrolled',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '秋葉  友良',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
      {
        id: 'B13630030',
        name: '数値解析論',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630030&je_cd=1',
        status: 'enrolled',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '南　哲人',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
      {
        id: 'B13610100',
        name: '情報・知能工学実験',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13610100&je_cd=1',
        status: 'enrolled',
        required: '[必修]',
        term: '通年',
        units: '4単位',
        staff: 'Ｓ３系教務委員',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
    ],
    [
      {
        id: 'B13630210',
        name: 'ソフトウェア設計論',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630210&je_cd=1',
        status: 'enrolled',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '佐藤　幸紀',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
      null,
      {
        id: 'B13630250',
        name: '情報セキュリティ',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630250&je_cd=1',
        status: 'enrolled',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '鈴木　幸太郎',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
      null,
      {
        id: 'B13610100',
        name: '情報・知能工学実験',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13610100&je_cd=1',
        status: 'enrolled',
        required: '[必修]',
        term: '通年',
        units: null,
        staff: 'Ｓ３系教務委員',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
    ],
    [
      {
        id: 'B13630330',
        name: 'ディジタル信号処理',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630330&je_cd=1',
        status: 'enrolled',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '松井　淑恵',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
      null,
      null,
      {
        id: 'B13630220',
        name: 'データベース',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630220&je_cd=1',
        status: 'enrolled',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '南　哲人',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
      {
        id: 'B13610100',
        name: '情報・知能工学実験',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13610100&je_cd=1',
        status: 'enrolled',
        required: '[必修]',
        term: '通年',
        units: null,
        staff: 'Ｓ３系教務委員',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
    ],
    [
      null,
      {
        id: 'B13630370',
        name: 'データサイエンス演習基礎',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630370&je_cd=1',
        status: 'enrolled',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '1単位',
        staff: '原田  耕治',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
      null,
      null,
      null,
    ],
  ],
  secondHalf: [
    [
      {
        id: 'B13630160',
        name: 'プログラム言語論',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630160&je_cd=1',
        status: 'enrolled',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '梅村　恭司',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
      {
        id: 'B13630240',
        name: '多変量解析論',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630240&je_cd=1',
        status: 'enrolled',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '岡田  美智男',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
      {
        id: 'B13630190',
        name: '制御工学',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630190&je_cd=1',
        status: 'enrolled',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '福村  直博',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
      {
        id: 'B10233610',
        name: '健康科学',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B10233610&je_cd=1',
        status: 'lot_rejected',
        required: '[選択]',
        term: '後期',
        units: '2単位',
        staff: '小島　俊男',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
      {
        id: 'B10233553',
        name: '欧米文化論',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B10233553&je_cd=1',
        status: 'lot_rejected',
        required: '[選択]',
        term: '後期',
        units: '2単位',
        staff: '社河内　友里',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
    ],
    [
      {
        id: 'B13630270',
        name: 'オペレーティングシステム',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630270&je_cd=1',
        status: 'enrolled',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '大村　廉',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
      null,
      {
        id: 'B1042504o',
        name: '国語表現法',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B1042504o&je_cd=1',
        status: 'lot_rejected',
        required: '[選択必修Ⅱ]',
        term: '後期',
        units: '2単位',
        staff: '日比野  浩信',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
      null,
      {
        id: 'B1033035d',
        name: '英語 Reading & Writing Ⅳ',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B1033035d&je_cd=1',
        status: 'enrolled',
        required: '[英語]',
        term: '後期',
        units: '1単位',
        staff: 'Levin David Michael',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
    ],
    [
      {
        id: 'B1033207a',
        name: 'フランス語Ⅲ',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B1033207a&je_cd=1',
        status: 'lot_rejected',
        required: '[フランス語]',
        term: '後期',
        units: '1単位',
        staff: '山崎  由佳',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
      null,
      {
        id: 'B13630280',
        name: 'コンパイラ',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630280&je_cd=1',
        status: 'enrolled',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '秋葉  友良',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
      {
        id: 'B13630030',
        name: '数値解析論',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630030&je_cd=1',
        status: 'enrolled',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '南　哲人',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
      {
        id: 'B13610100',
        name: '情報・知能工学実験',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13610100&je_cd=1',
        status: 'enrolled',
        required: '[必修]',
        term: '通年',
        units: '4単位',
        staff: 'Ｓ３系教務委員',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
    ],
    [
      {
        id: 'B13630210',
        name: 'ソフトウェア設計論',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630210&je_cd=1',
        status: 'enrolled',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '佐藤　幸紀',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
      null,
      {
        id: 'B13630250',
        name: '情報セキュリティ',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630250&je_cd=1',
        status: 'enrolled',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '鈴木　幸太郎',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
      null,
      {
        id: 'B13610100',
        name: '情報・知能工学実験',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13610100&je_cd=1',
        status: 'enrolled',
        required: '[必修]',
        term: '通年',
        units: null,
        staff: 'Ｓ３系教務委員',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
    ],
    [
      {
        id: 'B13630330',
        name: 'ディジタル信号処理',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630330&je_cd=1',
        status: 'enrolled',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '松井　淑恵',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
      null,
      null,
      {
        id: 'B13630220',
        name: 'データベース',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630220&je_cd=1',
        status: 'enrolled',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '2単位',
        staff: '南　哲人',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
      {
        id: 'B13610100',
        name: '情報・知能工学実験',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13610100&je_cd=1',
        status: 'enrolled',
        required: '[必修]',
        term: '通年',
        units: null,
        staff: 'Ｓ３系教務委員',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
    ],
    [
      null,
      {
        id: 'B13630370',
        name: 'データサイエンス演習基礎',
        url: 'https://kyomu.office.tut.ac.jp/Portal/Public/Syllabus/DetailMain.aspx?student=1&lct_year=2024&lct_cd=B13630370&je_cd=1',
        status: 'enrolled',
        required: '[選択Ⅰ]',
        term: '後期',
        units: '1単位',
        staff: '原田  耕治',
        area: null,
        faculty: null,
        grade: null,
        room: null,
      },
      null,
      null,
      null,
    ],
  ],
  intensive: [
    [null, null, null, null, null, null],
    [null, null, null, null, null, null],
    [null, null, null, null, null, null],
  ],
};
