name: publish package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Create tarball
        run: npm pack

      - name: Publish package
        uses: softprops/action-gh-release@v2
        with:
          files: timetable-scraper-*.tgz